[package]
name = "example"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "basic_motor"
path = "src/bin/basic_motor.rs"

[[bin]]
name = "encoder_monitor"
path = "src/bin/encoder_monitor.rs"

[[bin]]
name = "speed_control"
path = "src/bin/speed_control.rs"

[[bin]]
name = "direction_control"
path = "src/bin/direction_control.rs"

[[bin]]
name = "brake_test"
path = "src/bin/brake_test.rs"

[[bin]]
name = "stm32_motor"
path = "src/bin/stm32_motor.rs"

[dependencies]
motor-driver-hal = { path = ".." }
rppal = "0.22"
embedded-hal = "1.0.0"

# STM32 dependencies - uncomment for your STM32 family
stm32f4xx-hal = { version = "0.21", features = ["rt", "stm32f407"] }
cortex-m = "0.7"
cortex-m-rt = "0.7"
panic-halt = "0.2"
