[target.thumbv7em-none-eabihf]
runner = "gdb-multiarch -q -x openocd.gdb"
rustflags = [
  "-C", "linker=flip-link",
]

[build]
target = "thumbv7em-none-eabihf"    # Cortex-M4F and Cortex-M7F (with FPU)
# target = "thumbv7m-none-eabi"     # Cortex-M3
# target = "thumbv6m-none-eabi"     # Cortex-M0 and Cortex-M0+

[unstable]
build-std = ["core"]